language: go
go:
  - "1.15.x"
sudo: false
install:
  - GO111MODULE=on go install -v ./...
script:
  - export PATH=$PATH:$HOME/gopath/bin
  - export GO111MODULE=on
  - make fmt
  - make lint

  # Extend unit test timeout with travis_wait
  - travis_wait make unit-race

  - make unit-cover
